import{useEffect,useRef}from"react";
import{supabase}from"@/lib/supabaseClient";

const visitorKey="bytly_analytics_visitor_id";
const getVisitorId=()=>{let id=localStorage.getItem(visitorKey);if(!id){id=crypto.randomUUID();localStorage.setItem(visitorKey,id)}return id};
const path=()=>window.location.pathname+window.location.search;
const INTERNAL_HOSTS=["mybytly.com","www.mybytly.com"];\nconst isInternalHost=host=>{const h=(host||"").toLowerCase();return INTERNAL_HOSTS.includes(h)||/\\.vercel\\.app$/i.test(h)};\nconst normalizeSource=(source,medium,clickId)=>{const s=(source||"").toLowerCase().trim(),m=(medium||"").toLowerCase(),paid=!!clickId||/paid|cpc|ppc|ads|paid_social|display/i.test(m);const map={facebook:"فيسبوك",instagram:"إنستغرام",linkedin:"لينكدإن",whatsapp:"واتساب",google:"جوجل",x:"X",twitter:"X"};if(s==="direct")return{source:"direct",label:"مباشر",type:"direct"};if(isInternalHost(s))return{source:"internal",label:"داخل المنصة",type:"internal"};if(map[s])return{source:s,label:paid?map[s]+" – إعلان":map[s],type:paid?"paid":"referral"};return{source:"other",label:"إحالة أخرى",type:"referral"};};\nconst getAttribution=()=>{const u=new URL(window.location.href),q=u.searchParams,ref=document.referrer||"",host=(()=>{try{return ref?new URL(ref).hostname:""}catch{return""}})();let source=q.get("utm_source")||q.get("source")||"",medium=q.get("utm_medium")||"";const campaign=q.get("utm_campaign")||"",content=q.get("utm_content")||"",term=q.get("utm_term")||"",clickId=q.get("fbclid")?"facebook":q.get("gclid")?"google":q.get("msclkid")?"microsoft":"";if(!source&&clickId)source=clickId;if(!medium&&clickId)medium="paid";if(!source&&host&&!isInternalHost(host)){if(/facebook|fb\\.com/i.test(host))source="facebook";else if(/instagram/i.test(host))source="instagram";else if(/linkedin/i.test(host))source="linkedin";else if(/whatsapp/i.test(host))source="whatsapp";else if(/t\\.co|twitter|x\\.com/i.test(host))source="x";else if(/google/i.test(host))source="google";else source=host;}if(!source)source="direct";const n=normalizeSource(source,medium,clickId),current={source:n.source,medium,campaign,content,term,referrer:ref,label:n.label,type:n.type};try{const existing=JSON.parse(localStorage.getItem("bytly_acquisition_attribution")||"null");if(existing?.source&&existing.source!=="direct"&&existing.source!=="internal")return existing;localStorage.setItem("bytly_acquisition_attribution",JSON.stringify(current))}catch{}return current;};
const device=()=>/Mobi|Android|iPhone|iPad/i.test(navigator.userAgent)?"mobile":"desktop";
const os=()=>/iPhone|iPad|iPod/i.test(navigator.userAgent)?"iOS":/Android/i.test(navigator.userAgent)?"Android":/Windows/i.test(navigator.userAgent)?"Windows":/Mac OS X/i.test(navigator.userAgent)?"macOS":/Linux/i.test(navigator.userAgent)?"Linux":"Unknown";
const browser=()=>/Edg\//.test(navigator.userAgent)?"Edge":/Chrome\//.test(navigator.userAgent)?"Chrome":/Safari\//.test(navigator.userAgent)&&!/Chrome\//.test(navigator.userAgent)?"Safari":/Firefox\//.test(navigator.userAgent)?"Firefox":"Other";

export default function AnalyticsTracker(){
 const sessionRef=useRef(null),visitorRef=useRef(null),userRef=useRef(null),maxScrollRef=useRef(0);
 useEffect(()=>{if(!supabase)return;let mounted=true,heartbeat,routeWatcher,observer,authSubscription;
 let started=Date.now(),eventCount=0,pageCount=0,lastPath="",lastSection="";
 const start=async()=>{
  try{
   visitorRef.current=getVisitorId();
   const{data:{user}}=await supabase.auth.getUser();userRef.current=user?.id||null;
   let country="Unknown";
   try{const r=await fetch("https://ipapi.co/json/",{headers:{Accept:"application/json"}});if(r.ok){const j=await r.json();country=j.country_name||j.country||"Unknown"}}catch{}
   const attribution=getAttribution();\n   const storageKey="bytly_analytics_session";\n   let persisted=null;try{persisted=JSON.parse(sessionStorage.getItem(storageKey)||"null")}catch{}\n   const persistedAge=persisted?.startedAt?Date.now()-Number(persisted.startedAt):Infinity;\n   let sessionId=persisted?.id;let sessionStartedAt=persisted?.startedAt||Date.now();\n   if(!sessionId||persistedAge>30*60*1000){sessionId=crypto.randomUUID();sessionStartedAt=Date.now();try{sessionStorage.setItem(storageKey,JSON.stringify({id:sessionId,startedAt:sessionStartedAt}))}catch{}\n    const{error}=await supabase.from("analytics_sessions").insert({id:sessionId,user_id:userRef.current,visitor_id:visitorRef.current,entry_page:path(),browser:browser(),operating_system:os(),device_type:device(),country,traffic_source:attribution.source,traffic_medium:attribution.medium||null,traffic_campaign:attribution.campaign||null,traffic_content:attribution.content||null,traffic_term:attribution.term||null,referrer_url:attribution.referrer||null,attribution_type:attribution.type,attribution_label:attribution.label});\n    if(error){console.warn("Analytics session insert failed",error);return}\n   }\n   sessionRef.current=sessionId;started=sessionStartedAt;
