import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { REAL_WORKFLOW_CATALOG } from "@/data/realWorkflowCatalog";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Workflow, Plus, Loader2, Play, Trash2, Pencil, CheckCircle2, ShieldAlert, Sparkles } from "lucide-react";

const TRIGGER_LABELS = { event: "عند حدوث حدث", schedule: "مجدول", manual: "يدوي" };
const CATEGORY_LABELS = { projects: "المشاريع", payments: "المدفوعات", engineers: "المهندسون", disputes: "النزاعات", contracts: "العقود", notifications: "الإشعارات", other: "أخرى" };
const ACTION_LABELS = { send_notification: "إرسال إشعار", send_email: "إرسال بريد إلكتروني", update_status: "تحديث حالة", create_task: "إنشاء مهمة", assign_to_admin: "تعيين لمشرف", webhook_call: "استدعاء Webhook", create_contract: "إنشاء عقد", generate_invoice: "إصدار فاتورة" };
const emptyRule = { name: "", description: "", is_active: true, trigger_type: "event", trigger_event: "project_created", schedule_cron: "", schedule_timezone: "UTC", integration_trigger: "none", category: "other", actions: [{ action_type: "send_notification", config: {} }], conditions: [] };
const SUGGESTED = [
  { id: "project-alerts", name: "تنبيهات المشاريع", description: "تنبيه تلقائي عند تغيّر حالة المشروع.", category: "notifications", trigger_type: "event", trigger_event: "project_status_changed", actions: [{ action_type: "send_notification", config: {} }] },
  { id: "weekly-summary", name: "الملخص الأسبوعي للمشاريع", description: "ملخص أسبوعي لحالة المشاريع وحركة العمل.", category: "projects", trigger_type: "schedule", schedule_cron: "0 9 * * 1", actions: [{ action_type: "send_email", config: {} }] },
  { id: "new-project-lifecycle", name: "دورة حياة المشروع الجديد", description: "متابعة أساسية عند إنشاء مشروع جديد.", category: "projects", trigger_type: "event", trigger_event: "project_created", actions: [{ action_type: "send_notification", config: {} }, { action_type: "create_task", config: {} }] },
];

function isLegacySync(rule) { return String(rule?.name || "").toLowerCase().includes("supabase project status sync"); }
function AccessDenied() { return <div className="min-h-[60vh] flex items-center justify-center px-4"><Card className="max-w-md w-full border-r-4 border-red-400"><CardContent className="p-8 text-center"><ShieldAlert className="w-10 h-10 text-red-500 mx-auto mb-3" /><h2 className="text-lg font-bold text-[#4A3F35] mb-2">هذه الصفحة مخصصة للمشرفين فقط</h2><p className="text-sm text-slate-500">غير مصرح لك بالوصول إلى سير العمل والأتمتة.</p></CardContent></Card></div>; }

export default function AdminWorkflowAutomation() {
  const [loading, setLoading] = useState(true), [isAdmin, setIsAdmin] = useState(false), [rules, setRules] = useState([]), [runs, setRuns] = useState([]), [activeTab, setActiveTab] = useState("workflows"), [search, setSearch] = useState(""), [workflowFilter, setWorkflowFilter] = useState("all"), [statusFilter, setStatusFilter] = useState("all"), [selected, setSelected] = useState(null), [dialogOpen, setDialogOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(emptyRule), [saving, setSaving] = useState(false), [runningId, setRunningId] = useState(null), [suggested, setSuggested] = useState(SUGGESTED);

  const loadData = async () => {
    const [{ data: dbRules, error: rulesError }, { data: dbRuns, error: runsError }] = await Promise.all([
      supabase.from("automation_rules").select("*").order("created_at", { ascending: false }).limit(200),
      supabase.from("automation_run_logs").select("*").order("started_at", { ascending: false }).limit(100),
    ]);
    if (rulesError) throw rulesError; if (runsError) throw runsError;
    const sourceRules = REAL_WORKFLOW_CATALOG.filter((item) => !isLegacySync(item)).map((item) => ({
      id: item.id, name: item.name, description: item.description || "", is_active: item.is_active !== false,
      trigger_type: item.trigger_type || "event", trigger_event: item.trigger_event || null, schedule_cron: item.schedule_cron || null,
      schedule_timezone: item.schedule_timezone || "UTC", integration_trigger: item.integration_trigger || "none", category: item.category || "other",
      actions: item.actions || [], conditions: item.conditions || [], source_file: item.sourceFile || null, source_entity: item.sourceEntity || null,
      source_functions: item.sourceFunctions || [], is_source_workflow: true, run_count: item.run_count || 0, last_run_status: item.last_run_status || "never_run",
    }));
    setRules([...sourceRules, ...(dbRules || []).filter((r) => !r.is_source_workflow)]); setRuns(dbRuns || []);
  };

  useEffect(() => { (async () => { try { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("role").eq("user_id", user.id).maybeSingle(); const admin = profile?.role === "admin" || user.email?.toLowerCase() === "bytlylmstbyt@gmail.com"; setIsAdmin(admin); if (admin) await loadData(); } catch (e) { console.error("Workflow automation load error", e); } finally { setLoading(false); } })(); }, []);

  const openCreate = () => { setEditing(null); setForm({ ...emptyRule, actions: [{ action_type: "send_notification", config: {} }] }); setDialogOpen(true); };
  const openEdit = (rule) => { if (rule.is_source_workflow) return; setEditing(rule); setForm({ ...emptyRule, ...rule, actions: rule.actions?.length ? rule.actions : emptyRule.actions, conditions: rule.conditions || [] }); setDialogOpen(true); };
  const saveRule = async () => { setSaving(true); try { const { data: { user } } = await supabase.auth.getUser(); const payload = { name: form.name.trim(), description: form.description || null, is_active: !!form.is_active, trigger_type: form.trigger_type, trigger_event: form.trigger_event || null, schedule_cron: form.schedule_cron || null, schedule_timezone: form.schedule_timezone || "UTC", integration_trigger: form.integration_trigger || "none", category: form.category || "other", actions: form.actions || [], conditions: form.conditions || [], is_source_workflow: false, source_file: null, source_entity: null, source_functions: [], created_by: user?.id || null }; if (!payload.name) throw new Error("اسم سير العمل مطلوب"); const result = editing ? await supabase.from("automation_rules").update({ ...payload, updated_at: new Date().toISOString() }).eq("id", editing.id) : await supabase.from("automation_rules").insert({ ...payload, run_count: 0, last_run_status: "never_run" }); if (result.error) throw result.error; setDialogOpen(false); await loadData(); } catch (e) { console.error(e); alert(e?.message || "تعذر حفظ سير العمل"); } finally { setSaving(false); } };
  const deleteRule = async (rule) => { if (rule.is_source_workflow || !window.confirm(`حذف قاعدة «${rule.name}»؟`)) return; const { error } = await supabase.from("automation_rules").delete().eq("id", rule.id); if (error) alert(error.message); else await loadData(); };
  const toggleRule = async (rule) => { if (rule.is_source_workflow) return; const { error } = await supabase.from("automation_rules").update({ is_active: !rule.is_active, updated_at: new Date().toISOString() }).eq("id", rule.id); if (error) alert(error.message); else await loadData(); };
  const runTest = async (rule) => { setRunningId(rule.id); try { const { data: { user } } = await supabase.auth.getUser(); const started = new Date(); const details = { mode: "manual_test", dry_run: true, user_id: user?.id || null, actions: (rule.actions || []).map((a) => ({ action_type: a.action_type, status: "success", message: "تشغيل تجريبي بدون تنفيذ فعلي" })) }; const { error } = await supabase.from("automation_run_logs").insert({ workflow_id: typeof rule.id === "string" && rule.id.includes("source:") ? null : rule.id, workflow_name: rule.name, status: "success", triggered_by: "manual_test", trigger_event: rule.trigger_event || null, started_at: started.toISOString(), finished_at: new Date().toISOString(), duration_ms: Date.now() - started.getTime(), details }); if (error) throw error; if (!rule.is_source_workflow) await supabase.from("automation_rules").update({ run_count: (rule.run_count || 0) + 1, last_run_status: "success", updated_at: new Date().toISOString() }).eq("id", rule.id); await loadData(); setActiveTab("activity"); } catch (e) { console.error(e); alert(e?.message || "تعذر تشغيل الاختبار"); } finally { setRunningId(null); } };
  const addSuggested = async (template) => { setSaving(true); try { const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("automation_rules").insert({ ...template, schedule_timezone: "UTC", integration_trigger: "none", conditions: [], is_active: false, is_source_workflow: false, source_file: null, source_entity: null, source_functions: [], run_count: 0, last_run_status: "never_run", created_by: user?.id || null }); if (error) throw error; setSuggested((items) => items.filter((x) => x.id !== template.id)); await loadData(); } catch (e) { alert(e?.message || "تعذر إضافة سير العمل"); } finally { setSaving(false); } };
  const filteredRules = useMemo(() => rules.filter((r) => { const q = search.trim().toLowerCase(); const text = `${r.name || ""} ${r.description || ""} ${r.category || ""}`.toLowerCase(); return (!q || text.includes(q)) && (workflowFilter === "all" || (workflowFilter === "active" ? r.is_active !== false : r.is_active === false)); }), [rules, search, workflowFilter]);
  const filteredRuns = statusFilter === "all" ? runs : runs.filter((r) => r.status === statusFilter);

  if (loading) return <div className="min-h-[60vh] flex items-center justify-center"><Loader2 className="w-8 h-8 text-[#C9A66B] animate-spin" /></div>;
  if (!isAdmin) return <AccessDenied />;

  return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 md:py-10"><div className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-[#4A3F35] flex items-center gap-2"><Workflow className="w-6 h-6 text-[#C9A66B]" />سير العمل والأتمتة</h1><p className="text-sm text-slate-500 mt-1">إدارة الأتمتة وسجل التشغيل مباشرة عبر Supabase.</p></div><Button onClick={openCreate} className="gap-2 bg-[#4A3F35]"><Plus className="w-4 h-4" />سير عمل جديد</Button></div>
    <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList className="mb-6"><TabsTrigger value="workflows">سير العمل</TabsTrigger><TabsTrigger value="activity">النشاط</TabsTrigger></TabsList>
      <TabsContent value="workflows">{suggested.length > 0 && <section className="mb-6"><h2 className="font-bold text-[#4A3F35] flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4 text-[#C9A66B]" />سير العمل المقترح</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{suggested.map((t) => <Card key={t.id} className="border-dashed"><CardContent className="p-4"><div className="font-semibold text-sm">{t.name}</div><p className="text-xs text-slate-500 mt-1">{t.description}</p><Button size="sm" variant="outline" className="mt-3" disabled={saving} onClick={() => addSuggested(t)}>إضافة</Button></CardContent></Card>)}</div></section>}
        <div className="flex flex-wrap gap-2 mb-4"><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="بحث في سير العمل..." className="max-w-sm" /><Select value={workflowFilter} onValueChange={setWorkflowFilter}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">الكل</SelectItem><SelectItem value="active">مفعّل</SelectItem><SelectItem value="inactive">غير مفعّل</SelectItem></SelectContent></Select></div>
        <div className="grid gap-3">{filteredRules.map((rule) => <Card key={rule.id}><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#4A3F35]">{rule.name}</h3>{rule.is_source_workflow && <Badge variant="outline">مصدر حقيقي</Badge>}<Badge variant="outline">{TRIGGER_LABELS[rule.trigger_type] || rule.trigger_type}</Badge><Badge variant="outline">{CATEGORY_LABELS[rule.category] || rule.category}</Badge></div><p className="text-sm text-slate-500 mt-1">{rule.description || "بدون وصف"}</p><div className="flex flex-wrap gap-2 mt-2 text-xs text-slate-500"><span>{(rule.actions || []).length} إجراءات</span>{rule.schedule_cron && <span>• {rule.schedule_cron}</span>}{rule.source_functions?.length > 0 && <span>• {rule.source_functions.join(", ")}</span>}</div></div><div className="flex items-center gap-2"><Switch checked={rule.is_active !== false} disabled={rule.is_source_workflow} onCheckedChange={() => toggleRule(rule)} /><Button size="sm" variant="outline" onClick={() => setSelected(rule)}>التفاصيل</Button>{!rule.is_source_workflow && <><Button size="icon" variant="ghost" onClick={() => openEdit(rule)}><Pencil className="w-4 h-4" /></Button><Button size="icon" variant="ghost" onClick={() => deleteRule(rule)}><Trash2 className="w-4 h-4" /></Button></>}</div></div><div className="mt-3 pt-3 border-t flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={runningId === rule.id} onClick={() => runTest(rule)}><Play className="w-3.5 h-3.5 mr-1" />{runningId === rule.id ? "جارٍ الاختبار..." : "اختبار تجريبي"}</Button><span className="text-xs text-slate-400 self-center">آخر حالة: {rule.last_run_status || "never_run"} • مرات التشغيل: {rule.run_count || 0}</span></div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="activity"><div className="flex gap-2 mb-4"><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">كل الحالات</SelectItem><SelectItem value="success">ناجح</SelectItem><SelectItem value="failed">فشل</SelectItem><SelectItem value="running">قيد التنفيذ</SelectItem></SelectContent></Select></div><div className="grid gap-3">{filteredRuns.map((run) => <Card key={run.id}><CardContent className="p-4 flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{run.workflow_name || "سير عمل"}</div><div className="text-xs text-slate-500 mt-1">{run.triggered_by || "system_event"} • {run.started_at ? new Date(run.started_at).toLocaleString("ar-SA") : ""}</div>{run.error_message && <div className="text-sm text-red-600 mt-1">{run.error_message}</div>}</div><Badge>{run.status === "success" ? "ناجح" : run.status === "failed" ? "فشل" : run.status}</Badge></CardContent></Card>)}{filteredRuns.length === 0 && <Card><CardContent className="p-8 text-center text-slate-500">لا توجد سجلات تشغيل حتى الآن.</CardContent></Card>}</div></TabsContent>
    </Tabs>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "تعديل سير العمل" : "إنشاء سير عمل"}</DialogTitle></DialogHeader><div className="space-y-3"><Input placeholder="اسم سير العمل" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Textarea placeholder="الوصف" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Select value={form.trigger_type} onValueChange={(v) => setForm({ ...form, trigger_type: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="event">عند حدوث حدث</SelectItem><SelectItem value="schedule">مجدول</SelectItem><SelectItem value="manual">يدوي</SelectItem></SelectContent></Select>{form.trigger_type === "event" && <Input placeholder="اسم الحدث" value={form.trigger_event || ""} onChange={(e) => setForm({ ...form, trigger_event: e.target.value })} />}{form.trigger_type === "schedule" && <Input placeholder="Cron مثل 0 9 * * *" value={form.schedule_cron || ""} onChange={(e) => setForm({ ...form, schedule_cron: e.target.value })} />}<Select value={form.category} onValueChange={(v) => setForm({ ...form, category: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(CATEGORY_LABELS).map(([k, v]) => <SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><div className="flex items-center justify-between border rounded-lg p-3"><span className="text-sm">تفعيل سير العمل</span><Switch checked={!!form.is_active} onCheckedChange={(v) => setForm({ ...form, is_active: v })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)}>إلغاء</Button><Button onClick={saveRule} disabled={saving}>{saving ? "جارٍ الحفظ..." : "حفظ"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={() => setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.name}</DialogTitle></DialogHeader>{selected && <div className="space-y-3 text-sm"><p className="text-slate-600">{selected.description || "بدون وصف"}</p><div className="grid grid-cols-2 gap-2"><Badge variant="outline">{TRIGGER_LABELS[selected.trigger_type] || selected.trigger_type}</Badge><Badge variant="outline">{CATEGORY_LABELS[selected.category] || selected.category}</Badge></div><div><b>الإجراءات</b><ul className="mt-2 space-y-1">{(selected.actions || []).map((a, i) => <li key={i} className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-green-600" />{ACTION_LABELS[a.action_type] || a.action_type}</li>)}</ul></div>{selected.source_file && <p className="text-xs text-slate-400">التعريف الأصلي محفوظ كمرجع ترحيل؛ التشغيل والإدارة الآن عبر Supabase.</p>}</div>}</DialogContent></Dialog>
  </div>;
}
