import React,{useEffect,useMemo,useState}from"react";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
import{Activity,Clock,Globe2,MousePointerClick,RefreshCw,Users,Monitor,PlayCircle,TrendingUp}from"lucide-react";
import{ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip}from"recharts";
import{supabase}from"@/lib/supabaseClient";

const number=v=>new Intl.NumberFormat("ar-SA").format(v||0);
const duration=s=>{const x=Math.max(0,Math.floor(s||0));return x<60?x+" ث":Math.floor(x/60)+" د "+x%60+" ث"};
const countBy=(rows,getKey)=>{const m={};rows.forEach(row=>{const k=getKey(row)||"غير محدد";m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,8)};
const Empty=()=> <div className="p-8 text-center text-slate-400">لا توجد بيانات بعد.</div>;

export default function AdminAnalytics(){
 const[sessions,setSessions]=useState([]),[events,setEvents]=useState([]),[profiles,setProfiles]=useState([]),[clients,setClients]=useState([]),[range,setRange]=useState(7),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[selected,setSelected]=useState(null),[tick,setTick]=useState(Date.now());
 const load=async(manual=false)=>{setLoading(true);if(manual)setRefreshing(true);try{const{data,error}=await supabase.functions.invoke("admin-analytics",{body:{range}});if(error)throw error;if(data?.error)throw new Error(data.error);setSessions(data?.sessions||[]);setEvents(data?.events||[]);setProfiles(data?.profiles||[]);setClients(data?.clients||[])}catch(error){console.error("admin analytics load:",error);setSessions([]);setEvents([]);setProfiles([]);setClients([])}finally{setLoading(false);if(manual)setRefreshing(false)}};
 useEffect(()=>{load();const timer=setInterval(()=>{setTick(Date.now());load()},30000);return()=>clearInterval(timer)},[range]);
 const profileById=useMemo(()=>{const m=Object.fromEntries(profiles.map(p=>[p.user_id,p]));clients.forEach(c=>{if(c.user_id&&!m[c.user_id])m[c.user_id]={...c,role:"client"}});return m},[profiles,clients]); const activeSessions=useMemo(()=>sessions.filter(s=>tick-new Date(s.last_seen_at||s.started_at).getTime()<=90000),[sessions,tick]); const stats=useMemo(()=>({sessions:sessions.length,visitors:new Set(sessions.map(x=>x.visitor_id)).size,users:new Set(sessions.filter(x=>x.user_id).map(x=>x.user_id)).size,events:events.length,avg:sessions.length?sessions.reduce((a,x)=>a+(x.duration_seconds||0),0)/sessions.length:0,scroll:sessions.length?sessions.reduce((a,x)=>a+(x.max_scroll_percent||0),0)/sessions.length:0}),[sessions,events]);
 const countries=countBy(sessions,x=>x.country), browsers=countBy(sessions,x=>x.browser), systems=countBy(sessions,x=>x.operating_system), devices=countBy(sessions,x=>x.device_type);
 const pages=countBy(events.filter(x=>x.event_name==="page_view"),x=>x.page_path);
 const traffic=useMemo(()=>{const out=[];const now=new Date();const todayKey=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(now);const [ty,tm,td]=todayKey.split("-").map(Number);const start=new Date(Date.UTC(ty,tm-1,td-(range===1?0:range-1),-3,0,0));const days=range===1?1:range;for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10);const daySessions=sessions.filter(s=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(s.started_at))===key);const dayEvents=events.filter(e=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(e.occurred_at))===key);out.push({date:range===1?d.toLocaleTimeString("ar-SA",{hour:"2-digit",minute:"2-digit"}):d.toLocaleDateString("ar-SA",{day:"numeric",month:"short"}),sessions:daySessions.length,users:new Set(daySessions.filter(s=>s.user_id).map(s=>s.user_id)).size,events:dayEvents.length});}return out},[sessions,events,range]);
 const actions=countBy(events.filter(x=>x.event_name==="click"),x=>x.metadata?.label||"نقر غير مسمى");
 const sections=countBy(events.filter(x=>x.event_name==="section_view"),x=>x.section_name||x.metadata?.title);
 const loginCount=events.filter(x=>x.event_name==="click"&&/login|sign_in|تسجيل|دخول/i.test(x.metadata?.label||"")).length;
 const replay=selected?events.filter(x=>x.session_id===selected.id).sort((a,b)=>new Date(a.occurred_at)-new Date(b.occurred_at)):[];
 return <div dir="rtl" className="max-w-7xl mx-auto px-4 py-8 space-y-6">
  <div className="flex items-center justify-between flex-wrap gap-3"><div><p className="text-xs text-[#C9A66B]">مجلس الإدارة / المستخدمون</p><h1 className="text-2xl font-bold text-[#4A3F35]">تحليلات المستخدمين والجلسات</h1><p className="text-sm text-slate-500">بيانات حقيقية من Supabase.</p></div><div className="flex gap-2"><select value={range} onChange={e=>setRange(Number(e.target.value))} className="border rounded-lg px-3 py-2"><option value="1">اليوم</option><option value="7">7 أيام</option><option value="30">30 يوم</option></select><button type="button" onClick={()=>load(true)} disabled={loading||refreshing} className="border rounded-lg px-3 py-2 disabled:opacity-50 disabled:cursor-not-allowed" title="تحديث البيانات"><RefreshCw className={`w-4 h-4 ${refreshing?"animate-spin":""}`}/></button></div></div>
  <Card className="border-2 border-green-200 bg-green-50"><CardContent className="p-4"><div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-green-500 animate-pulse"/><span className="font-semibold text-green-800">نشط الآن</span></div><div className="text-3xl font-bold text-green-800 mt-2">{number(activeSessions.length)}</div><div className="text-xs text-green-700 mt-1">جلسات نشطة خلال آخر 90 ثانية</div></CardContent></Card><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{[["الجلسات",stats.sessions,Activity],["الزوار",stats.visitors,Globe2],["المستخدمون",stats.users,Users],["متوسط الجلسة",duration(stats.avg),Clock],["الأحداث",stats.events,MousePointerClick],["متوسط التمرير",Math.round(stats.scroll)+"%",Activity]].map(([label,value,Icon])=><Card key={label}><CardContent className="p-4"><Icon className="w-4 h-4 text-[#C9A66B]"/><div className="text-xs text-slate-500 mt-2">{label}</div><div className="text-xl font-bold">{typeof value==="number"?number(value):value}</div></CardContent></Card>)}</div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="w-5 h-5 text-[#C9A66B]"/>حركة المرور داخل المنصة</CardTitle></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={traffic} margin={{top:10,right:10,left:0,bottom:5}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="sessions" name="الجلسات" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="users" name="المستخدمون" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="events" name="الأحداث" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><p className="text-xs text-slate-500 mt-2">يعرض الحركة حسب الفترة المختارة: اليوم، 7 أيام، أو 30 يوم.</p></CardContent></Card><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">{[["الدول",countries,Globe2],["المتصفحات",browsers,Monitor],["أنظمة التشغيل",systems,Monitor],["الأجهزة",devices,Monitor]].map(([title,data,Icon])=><Card key={title}><CardHeader><CardTitle className="text-base flex gap-2"><Icon className="w-4 h-4"/>{title}</CardTitle></CardHeader><CardContent>{data.length?data.map(([k,c])=><div key={k} className="flex justify-between border-b py-2 text-sm"><span>{k}</span><b>{number(c)}</b></div>):<Empty/>}</CardContent></Card>)}</div>
  <div className="grid lg:grid-cols-3 gap-5"><Card><CardHeader><CardTitle>الصفحات الأكثر مشاهدة</CardTitle></CardHeader><CardContent>{pages.length?pages.map(([k,c])=><div key={k} className="flex justify-between border-b py-2 text-sm"><span dir="ltr">{k}</span><b>{number(c)}</b></div>):<Empty/>}</CardContent></Card><Card><CardHeader><CardTitle>الأقسام التي تمت مشاهدتها</CardTitle></CardHeader><CardContent>{sections.length?sections.map(([k,c])=><div key={k} className="flex justify-between border-b py-2 text-sm"><span>{k}</span><b>{number(c)}</b></div>):<Empty/>}</CardContent></Card><Card><CardHeader><CardTitle>الإجراءات والدخول</CardTitle></CardHeader><CardContent><div className="text-3xl font-bold">{number(loginCount)}</div><div className="text-sm text-slate-500 mb-3">أحداث الدخول</div>{actions.map(([k,c])=><div key={k} className="flex justify-between border-b py-2 text-sm"><span>{k}</span><b>{number(c)}</b></div>)}</CardContent></Card></div>
  <Card><CardHeader><CardTitle className="flex items-center justify-between"><span>الجلسات النشطة الآن</span><span className="text-xs text-green-700">{number(activeSessions.length)} متصل</span></CardTitle></CardHeader><CardContent>{activeSessions.length?<div className="space-y-2">{activeSessions.map(s=>{const p=profileById[s.user_id];return <div key={s.id} className="flex items-center justify-between border rounded-lg p-3"><div><div className="font-semibold flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-500"/>{p?.full_name||p?.email||"زائر"}</div><div className="text-xs text-slate-500">{s.device_type||"—"} · {s.operating_system||"—"} · {s.browser||"—"} · {s.country||"—"}</div></div><div className="text-xs text-slate-500">آخر نشاط {new Date(s.last_seen_at).toLocaleTimeString("ar-SA")}</div></div>})}</div>:<Empty/>}</CardContent></Card><Card><CardHeader><CardTitle>الجلسات المسجلة</CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto">{loading?<div className="p-8 text-center">جارٍ التحميل...</div>:<table className="w-full text-sm"><thead><tr className="border-b bg-slate-50">{["التاريخ","المستخدم/الزائر","الدولة","المدة","الجهاز","النظام","المتصفح","التمرير","الاستعراض"].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{sessions.map(s=><tr key={s.id} className="border-b"><td className="p-3 text-xs">{new Date(s.started_at).toLocaleString("ar-SA")}</td><td className="p-3">{s.user_id?(profileById[s.user_id]?.full_name||profileById[s.user_id]?.email||"مستخدم مسجل"):"زائر "+String(s.visitor_id||"").slice(0,8)}</td><td className="p-3">{s.country||"—"}</td><td className="p-3">{duration(s.duration_seconds)}</td><td className="p-3">{s.device_type||"—"}</td><td className="p-3">{s.operating_system||"—"}</td><td className="p-3">{s.browser||"—"}</td><td className="p-3">{s.max_scroll_percent||0}%</td><td className="p-3"><button onClick={()=>setSelected(s)} className="inline-flex gap-1 items-center border rounded-lg px-2 py-1"><PlayCircle className="w-4 h-4"/>استعراض</button></td></tr>)}</tbody></table>}</CardContent></Card>
  {selected&&<Card><CardHeader><CardTitle>استعراض أحداث الجلسة</CardTitle></CardHeader><CardContent><div className="grid md:grid-cols-4 gap-3 text-sm mb-4"><span>الدولة: <b>{selected.country}</b></span><span>الجهاز: <b>{selected.device_type}</b></span><span>النظام: <b>{selected.operating_system}</b></span><span>المتصفح: <b>{selected.browser}</b></span></div><div className="space-y-2 max-h-96 overflow-auto">{replay.map((e,i)=><div key={e.id} className="border rounded-lg p-3 flex gap-3"><b>{i+1}</b><div><strong>{e.event_name}</strong><div className="text-xs text-slate-500">{new Date(e.occurred_at).toLocaleTimeString("ar-SA")} — {e.section_name||e.page_path}</div>{e.metadata?.label&&<div className="text-sm">العنصر: {e.metadata.label}</div>}{e.metadata?.percent!=null&&<div className="text-sm">التمرير: {e.metadata.percent}%</div>}</div></div>)}</div><div className="mt-5 p-4 rounded-xl border bg-slate-50"><div className="font-semibold mb-2">الخصوصية في التسجيل</div><p className="text-xs text-slate-600">يتم تسجيل التفاعل والصفحات والأحداث فقط. لا يتم تسجيل كلمات المرور أو قيم حقول النماذج أو محتوى النصوص الحساسة.</p></div><p className="text-xs text-amber-700 mt-4">هذا استعراض زمني فعلي للأحداث. لا يوجد فيديو وهمي.</p></CardContent></Card>}
 </div>
}