import React,{useEffect,useMemo,useState}from"react";
import{Link}from"react-router-dom";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
import{HardHat,Building2,UserRound,Star,Handshake,ShieldCheck,ClipboardCheck,UserCog,Users,UserPlus,Activity,RefreshCw,Globe2,Monitor}from"lucide-react";
import{createPageUrl}from"@/utils";
import{supabase}from"@/lib/supabaseClient";

const roleLabel={admin:"مشرف",engineer:"مهندس",client:"عميل",contractor:"مقاول",supplier:"مورد",consultant:"استشاري",firm:"مكتب/شركة",investor:"مستثمر",developer:"مطور",user:"مستخدم"};
const sections=[{title:"إدارة المهندسين",desc:"المهندسون والملفات المهنية والاعتمادات",icon:HardHat,page:"AdminEngineers"},{title:"إدارة العملاء",desc:"حسابات العملاء وبياناتهم واحتياجاتهم",icon:UserRound,page:"AdminClients"},{title:"الشركات ومقدمو الخدمة",desc:"الشركات والمقاولون والاستشاريون والموردون",icon:Building2,page:"AdminProviders"},{title:"تقييمات العملاء",desc:"مراجعة تقييمات العملاء وملاحظاتهم",icon:Star,page:"AdminReviews"},{title:"علاقات العملاء CRM",desc:"متابعة العلاقات والتواصل وحالات العملاء",icon:Handshake,page:"AdminClients"},{title:"طلبات التسجيل والموافقات",desc:"مراجعة الطلبات والموافقات المعلقة",icon:ClipboardCheck,page:"PendingApprovals"},{title:"الأدوار والصلاحيات",desc:"إدارة أدوار المستخدمين وتعيين الصلاحيات",icon:ShieldCheck,page:"RoleManagement"},{title:"تعيين الأدوار للمستخدمين",desc:"تحديد الدور المناسب لكل موظف إداري",icon:UserCog,page:"UserRoleAssignment"}];

export default function AdminUserManagementCenter(){
 const[users,setUsers]=useState([]),[sessions,setSessions]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState("all"),[refreshing,setRefreshing]=useState(false);
 const load=async(manual=false)=>{
  if(!supabase)return;
  if(manual)setRefreshing(true);setLoading(true);
  const[{data:profiles,error:pErr},{data:sessionData,error:sErr}]=await Promise.all([
   supabase.from("profiles").select("id,user_id,full_name,email,role,phone,created_at,last_login_at,last_seen_at").order("created_at",{ascending:false}),
   supabase.from("analytics_sessions").select("id,user_id,visitor_id,started_at,last_seen_at,entry_page,browser,operating_system,device_type,country,duration_seconds").order("started_at",{ascending:false}).limit(1000)
  ]);
  if(pErr)console.error("Admin users load error:",pErr);if(sErr)console.error("Admin sessions load error:",sErr);
  setUsers(profiles||[]);setSessions(sessionData||[]);setLoading(false);if(manual)setRefreshing(false);
 };
 useEffect(()=>{load();const autoRefresh=setInterval(()=>load(),30000);const ch=supabase?.channel("admin-user-directory").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},load).subscribe();return()=>{clearInterval(autoRefresh);if(ch)supabase?.removeChannel(ch)}},[]);
 const now=Date.now(),todayStart=new Date();todayStart.setHours(0,0,0,0);
 const activeSessions=sessions.filter(s=>s.last_seen_at&&now-new Date(s.last_seen_at).getTime()<=300000);
 const newToday=users.filter(u=>new Date(u.created_at)>=todayStart),newWeek=users.filter(u=>now-new Date(u.created_at).getTime()<=604800000);
 const profileByUser=useMemo(()=>Object.fromEntries(users.map(u=>[u.user_id,u])),[users]);
 const registeredSessions=sessions.filter(s=>s.user_id),anonymousSessions=sessions.filter(s=>!s.user_id);
 const filtered=useMemo(()=>filter==="new"?newWeek:filter==="active"?activeSessions.map(s=>profileByUser[s.user_id]).filter(Boolean):filter==="engineer"?users.filter(u=>u.role==="engineer"):filter==="client"?users.filter(u=>u.role==="client"):users,[users,filter,activeSessions,profileByUser,newWeek]);
 return <div className="max-w-7xl mx-auto px-4 py-8 space-y-7"dir="rtl">
  <div className="flex items-center justify-between gap-3 flex-wrap"><div><p className="text-xs text-[#C9A66B] font-medium">مجلس الإدارة / الإدارة التنفيذية</p><h1 className="text-2xl font-bold text-[#4A3F35] mt-1">إدارة المستخدمين والزوار</h1><p className="text-sm text-slate-500 mt-1">سجل حي للحسابات المسجلة وكل من دخل المنصة، حتى الزائر الذي لم ينشئ حسابًا.</p></div><button type="button" onClick={()=>load(true)} disabled={loading||refreshing} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm disabled:opacity-50"><RefreshCw className={`w-4 h-4 ${refreshing?"animate-spin":""}`}/>{refreshing?"جارٍ التحديث...":"تحديث"}</button></div>
  <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[["الحسابات",users.length,Users],["نشط الآن",activeSessions.length,Activity],["جدد اليوم",newToday.length,UserPlus],["جدد 7 أيام",newWeek.length,UserPlus],["جلسات مسجلة",registeredSessions.length,Users],["زوار بلا حساب",anonymousSessions.length,Globe2]].map(([l,v,I])=><Card key={l}><CardContent className="p-4"><div className="flex items-center justify-between"><span className="text-xs text-slate-500">{l}</span><I className="w-4 h-4 text-[#C9A66B]"/></div><p className="text-2xl font-bold text-[#4A3F35] mt-2">{v}</p></CardContent></Card>)}</div>
  <div className="flex flex-wrap gap-2"><Link to={createPageUrl("AdminAnalytics")} className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-[#4A3F35] text-white text-sm font-semibold">📊 تحليلات المستخدمين والجلسات</Link>{[["all","كل الحسابات"],["new","الحسابات الجديدة"],["active","المسجلون النشطون"],["engineer","المهندسون"],["client","العملاء"]].map(([v,l])=><button key={v}onClick={()=>setFilter(v)}className={`px-4 py-2 rounded-full text-sm ${filter===v?"bg-[#4A3F35] text-white":"bg-slate-100 text-slate-700"}`}>{l}</button>)}</div>
  <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Users className="w-5 h-5 text-[#C9A66B]"/>دليل الحسابات <span className="text-xs font-normal text-slate-400">({filtered.length})</span></CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto">{loading?<div className="p-8 text-center text-slate-500">جارٍ تحميل البيانات...</div>:<table className="w-full text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500"><th className="p-3 text-right">الاسم</th><th className="p-3 text-right">النوع</th><th className="p-3 text-right">البريد</th><th className="p-3 text-right">الجوال</th><th className="p-3 text-right">التسجيل</th><th className="p-3 text-right">آخر دخول</th><th className="p-3 text-right">النشاط</th></tr></thead><tbody>{filtered.map(u=>{const online=u.last_seen_at&&(now-new Date(u.last_seen_at).getTime()<=300000);return <tr key={u.id}className="border-b hover:bg-slate-50"><td className="p-3 font-medium">{u.full_name||"غير محدد"}</td><td className="p-3">{roleLabel[u.role]||u.role||"غير محدد"}</td><td className="p-3">{u.email||"—"}</td><td className="p-3">{u.phone||"—"}</td><td className="p-3 text-xs">{new Date(u.created_at).toLocaleString("ar-SA")}</td><td className="p-3 text-xs">{u.last_login_at?new Date(u.last_login_at).toLocaleString("ar-SA"):"لم يسجل الدخول بعد"}</td><td className={`p-3 ${online?"text-green-600":"text-slate-400"}`}>{online?"● نشط الآن":"○ غير نشط"}</td></tr>})}</tbody></table>}</CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="w-5 h-5 text-[#C9A66B]"/>كل من دخل المنصة <span className="text-xs font-normal text-slate-400">آخر 1000 جلسة</span></CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500"><th className="p-3 text-right">وقت الدخول</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">البريد / الزائر</th><th className="p-3 text-right">الصفحة</th><th className="p-3 text-right">الدولة</th><th className="p-3 text-right">الجهاز</th><th className="p-3 text-right">آخر نشاط</th></tr></thead><tbody>{sessions.map(s=>{const p=profileByUser[s.user_id];const online=s.last_seen_at&&(now-new Date(s.last_seen_at).getTime()<=300000);return <tr key={s.id}className="border-b hover:bg-slate-50"><td className="p-3 text-xs">{new Date(s.started_at).toLocaleString("ar-SA")}</td><td className="p-3">{s.user_id?<span className="text-green-600">حساب مسجل</span>:<span className="text-amber-600">زائر بدون حساب</span>}</td><td className="p-3">{p?.email||p?.full_name||(s.user_id?"مستخدم مسجل":"زائر "+String(s.visitor_id||"").slice(0,10))}</td><td className="p-3 text-xs"dir="ltr">{s.entry_page||"/"}</td><td className="p-3">{s.country||"—"}</td><td className="p-3">{s.device_type||"—"} · {s.browser||"—"}</td><td className={`p-3 text-xs ${online?"text-green-600":"text-slate-400"}`}>{online?"● الآن":s.last_seen_at?new Date(s.last_seen_at).toLocaleString("ar-SA"):"—"}</td></tr>})}</tbody></table>{!sessions.length&&!loading&&<div className="p-8 text-center text-slate-400">لا توجد جلسات بعد.</div>}</CardContent></Card>
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{sections.map(({title,desc,icon:Icon,page})=><Link key={title}to={createPageUrl(page)}><Card className="h-full hover:shadow-md transition-shadow"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base text-[#4A3F35]"><Icon className="w-5 h-5 text-[#C9A66B]"/>{title}</CardTitle></CardHeader><CardContent><p className="text-sm text-slate-500">{desc}</p></CardContent></Card></Link>)}</div>
 </div>
}