import React,{useEffect,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
export default function MCPConsent(){
 const q=new URLSearchParams(window.location.search),[state,setState]=useState({loading:true,error:"",client:"MCP Client"});
 useEffect(()=>{(async()=>{try{const s=await supabase.auth.getSession();if(!s.data?.session){window.location.replace("/login?from_url="+encodeURIComponent(window.location.pathname+window.location.search));return;}const r=await fetch("/api/mcp-oauth?action=begin&"+q.toString());const j=await r.json();if(!r.ok)throw new Error(j.error_description||j.error||"طلب تفويض غير صالح");setState({loading:false,error:"",client:j.client_name||q.get("client_id")||"MCP Client"});}catch(e){setState({loading:false,error:e.message||"تعذر التحقق",client:"MCP Client"});}})()},[]);
 const finish=async()=>{try{const s=await supabase.auth.getSession();if(!s.data?.session)throw new Error("انتهت جلسة الدخول");const r=await fetch("/api/mcp-oauth?action=approve",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+s.data.session.access_token},body:JSON.stringify({client_id:q.get("client_id"),redirect_uri:q.get("redirect_uri"),code_challenge:q.get("code_challenge"),state:q.get("state")})});const j=await r.json();if(!r.ok)throw new Error(j.error_description||j.error||"تعذر إتمام التفويض");window.location.replace(j.redirect_uri);}catch(e){setState(v=>({...v,error:e.message||"تعذر إتمام التفويض"}));}};
 if(state.loading)return <div dir="rtl" style={{padding:40,textAlign:"center"}}>جاري التحقق من طلب الوصول…</div>;
 if(state.error)return <div dir="rtl" style={{padding:40,textAlign:"center"}}><h2>تعذر التفويض</h2><p>{state.error}</p></div>;
 return <main dir="rtl" style={{minHeight:"100dvh",display:"flex",alignItems:"center",justifyContent:"center",background:"#f8fafc",padding:20}}><section style={{maxWidth:520,width:"100%",background:"#fff",padding:32,borderRadius:20,boxShadow:"0 10px 35px rgba(0,0,0,.08)"}}><h1 style={{marginTop:0}}>السماح بالوصول إلى بيتلي</h1><p>المساعد <b>{state.client}</b> يطلب الوصول إلى بيانات بيتلي المصرح بها لحسابك.</p><p style={{color:"#64748b"}}>لن يتمكن المساعد من الوصول إلى حسابات مستخدمين آخرين.</p><button onClick={finish} style={{width:"100%",padding:14,border:0,borderRadius:10,background:"#111827",color:"#fff",fontWeight:700,cursor:"pointer"}}>موافقة ومتابعة</button></section></main>;
}