import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";

const URL=process.env.VITE_SUPABASE_URL||"https://wbqtgdkubrocnqnykhlt.supabase.co";
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const BASE="https://www.mybytly.com";
const sha=s=>crypto.createHash("sha256").update(s).digest("hex");
const rand=()=>crypto.randomBytes(32).toString("base64url");
const db=()=>createClient(URL,KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const json=(res,status,b)=>{res.status(status);res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type,Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");return res.end(JSON.stringify(b));};
const bodyOf=req=>{if(req.body&&typeof req.body==="object")return req.body;const raw=typeof req.body==="string"?req.body:"";if(!raw)return{};try{return JSON.parse(raw)}catch{try{return Object.fromEntries(new URLSearchParams(raw).entries())}catch{return{}}}};
const allowed=(uris,uri)=>Array.isArray(uris)&&uris.includes(uri);
async function client(s,id,redirect){const {data:c,error}=await s.from("mcp_oauth_clients").select("*").eq("client_id",id).is("revoked_at",null).maybeSingle();if(error||!c||!allowed(c.redirect_uris,redirect))return null;return c}

export default async function handler(req,res){
 if(req.method==="OPTIONS")return res.status(204).setHeader("Access-Control-Allow-Origin","*").end();
 const action=String(req.query?.action||"");
 if(action==="metadata")return json(res,200,{issuer:BASE,authorization_endpoint:BASE+"/oauth/authorize",token_endpoint:BASE+"/oauth/token",registration_endpoint:BASE+"/oauth/register",response_types_supported:["code"],grant_types_supported:["authorization_code","refresh_token"],code_challenge_methods_supported:["S256"],scopes_supported:["mcp","offline_access"],token_endpoint_auth_methods_supported:["none"]});
 if(action==="resource")return json(res,200,{resource:BASE+"/api/mcp",authorization_servers:[BASE],scopes_supported:["mcp","offline_access"],bearer_methods_supported:["header"]});
 if(action==="register"){if(req.method!=="POST")return json(res,405,{error:"method_not_allowed"});let b=bodyOf(req);if(typeof b==="string")try{b=JSON.parse(b)}catch{};const uris=Array.isArray(b.redirect_uris)?b.redirect_uris.map(String):[];if(!uris.length||uris.some(u=>!/^https?:\/\//i.test(u)))return json(res,400,{error:"invalid_redirect_uris"});const id="bytly_"+rand(),s=db();const {error}=await s.from("mcp_oauth_clients").insert({client_id:id,client_name:String(b.client_name||"MCP Client").slice(0,120),redirect_uris:uris,client_type:"public"});if(error)return json(res,500,{error:"server_error"});return json(res,201,{client_id:id,client_name:String(b.client_name||"MCP Client").slice(0,120),redirect_uris:uris,token_endpoint_auth_method:"none"});}
 if(action==="begin"){if(req.method!=="GET"&&req.method!=="POST")return json(res,405,{error:"method_not_allowed"});const q=req.method==="GET"?req.query:(typeof req.body==="string"?JSON.parse(req.body||"{}"):bodyOf(req));const id=String(q.client_id||""),redirect=String(q.redirect_uri||"");if(q.response_type!=="code"||q.code_challenge_method!=="S256"||!id||!redirect||!q.code_challenge)return json(res,400,{error:"invalid_request"});const c=await client(db(),id,redirect);if(!c)return json(res,400,{error:"invalid_client_or_redirect"});return json(res,200,{client_id:c.client_id,client_name:c.client_name,redirect_uri:redirect,scope:String(q.scope||"mcp")});}
 if(action==="authorize"){const q=req.query||{};const p=new URLSearchParams(q);return res.redirect(302,"/mcp/consent?"+p.toString());}
 if(action==="approve"){if(req.method!=="POST")return json(res,405,{error:"method_not_allowed"});const b=bodyOf(req);const s=db(),c=await client(s,String(b.client_id),String(b.redirect_uri));if(!c)return json(res,400,{error:"invalid_client"});const token=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");const {data:{user}}=await s.auth.getUser(token);if(!user)return json(res,401,{error:"login_required"});const raw=rand();const {error}=await s.from("mcp_oauth_codes").insert({code_hash:sha(raw),client_id:c.client_id,user_id:user.id,redirect_uri:String(b.redirect_uri),code_challenge:String(b.code_challenge),code_challenge_method:"S256",scope:String(b.scope||"mcp"),expires_at:new Date(Date.now()+300000).toISOString()});if(error)return json(res,500,{error:"server_error"});const u=new URL(String(b.redirect_uri));u.searchParams.set("code",raw);if(b.state)u.searchParams.set("state",String(b.state));return json(res,200,{redirect_uri:u.toString()});}
 if(action==="token"){if(req.method!=="POST")return json(res,405,{error:"method_not_allowed"});let b=bodyOf(req);if(typeof b==="string")try{b=JSON.parse(b)}catch{};const s=db();
  if(b.grant_type==="refresh_token"){const {data:t}=await s.from("mcp_oauth_tokens").select("*").eq("refresh_token_hash",sha(String(b.refresh_token||""))).is("revoked_at",null).gt("refresh_expires_at",new Date().toISOString()).maybeSingle();if(!t||t.client_id!==String(b.client_id||""))return json(res,400,{error:"invalid_grant"});const access=rand();const nextRefresh=rand();const {error}=await s.from("mcp_oauth_tokens").update({access_token_hash:sha(access),refresh_token_hash:sha(nextRefresh),expires_at:new Date(Date.now()+3600000).toISOString(),refresh_expires_at:new Date(Date.now()+30*24*3600000).toISOString()}).eq("access_token_hash",t.access_token_hash);if(error)return json(res,500,{error:"server_error"});return json(res,200,{access_token:access,refresh_token:nextRefresh,token_type:"Bearer",expires_in:3600,scope:t.scope});}
  if(b.grant_type!=="authorization_code")return json(res,400,{error:"unsupported_grant_type"});const {data:c}=await s.from("mcp_oauth_codes").select("*").eq("code_hash",sha(String(b.code||""))).is("used_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(!c||c.client_id!==String(b.client_id||"")||c.redirect_uri!==String(b.redirect_uri||""))return json(res,400,{error:"invalid_grant"});const expected=crypto.createHash("sha256").update(String(b.code_verifier||"")).digest("base64url");if(expected!==c.code_challenge)return json(res,400,{error:"invalid_grant"});await s.from("mcp_oauth_codes").update({used_at:new Date().toISOString()}).eq("code_hash",c.code_hash);const access=rand(),refresh=rand();const {error}=await s.from("mcp_oauth_tokens").insert({access_token_hash:sha(access),refresh_token_hash:sha(refresh),client_id:c.client_id,user_id:c.user_id,scope:c.scope,expires_at:new Date(Date.now()+3600000).toISOString(),refresh_expires_at:new Date(Date.now()+30*24*3600000).toISOString()});if(error)return json(res,500,{error:"server_error"});return json(res,200,{access_token:access,refresh_token:refresh,token_type:"Bearer",expires_in:3600,scope:c.scope});}
 return json(res,404,{error:"not_found"});
}
